settings:
  name: Astra Family
  search: "astra-control-service,astra-control-center,astra-automation,trident"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: Astra product family documentation
      url: /index.html
