settings:
  name: Astra Family
  search: "astra-control-service,astra-control-center,astra-automation,trident"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: Astra product family documentation
      url: /index.html
product-family:
  sidebarlinks:
      - title: All products
        tags: tag_application_data_management,tag_storage_management,tag_data_storage,tag_api,tag_get_started
        class: active
      - title: Application data management
        tags: tag_application_data_management
      - title: Storage management
        tags: tag_storage_management
      - title: Automation and API
        tags: tag_api
  tiles:
    - title: "Learn about the Astra family"
      icon: ./media/Astra_Family_logo_line.png
      url: intro-family.html
      summary: "Learn about the Astra family of products."
      tags: all, tag_get_started
    - title: "Astra Control Service"
      icon: ./media/Astra_Control_logo_line.png
      url: https://docs.netapp.com/us-en/astra/index.html
      summary: "Use a service managed by NetApp for app-aware data management of Kubernetes workloads in public clouds."
      tags: all, tag_application_data_management
    - title: "Astra Control Center"
      icon: ./media/Astra_Control_logo_line.png
      url: https://docs.netapp.com/us-en/astra-control-center/index.html
      summary: "Use self-managed software for app-aware data management of on-premises Kubernetes workloads."
      tags: all, tag_application_data_management
    - title: "Astra Trident"
      icon: ./media/Astra_Trident_logo_line2.png
      url: https://docs.netapp.com/us-en/trident/index.html
      summary: "Use CSI compliant storage provisioning and management for Kubernetes workloads with NetApp storage providers."
      tags: all, tag_storage_management
    - title: "Astra Automation and API"
      icon: ./media/Astra_Family_logo_line.png
      url: https://docs.netapp.com/us-en/astra-automation/index.html
      summary: "Use an API and SDKs to automate Astra workflows in your operations."
      tags: all, tag_api
